# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(verbose_name=True)),
                ('flowchart_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('source_book', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(verbose_name=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storymanager.Story'),
        ),
    ]
